### ISSUE TITLE
Next.js 15 breaks alternate links

### ISSUE THREAD

**Issue by amannn** [amannn/next-intl#1442]
Recent canary versions of Next.js 15 as well as the stable version that was released yesterday break [alternate links](https://next-intl-docs.vercel.app/docs/routing#alternate-links) if you're using `next/font` or `next/image` with `priority`.

This header is important for apps that use i18n routing and the `alternateLinks` feature (which is turned on by default). Failing to return this header can result in content being marked as duplicate by search engines.

Upstream bug report: https://github.com/vercel/next.js/issues/69000#issuecomment-2416459189

I'm currently waiting for this to be resolved upstream before updating the examples and the bug repro to use Next.js 15.

As a workaround, you can use a [sitemap](https://next-intl-docs.vercel.app/docs/environments/actions-metadata-route-handlers#sitemap) to instruct search engines about multiple variants of your pages.

**Comment by Wiibleyde** [comment]
Hello, I think it's a part of the problem enounced here (if it's not i'm sorryyy), I have this error :
```
Error: Route "/[locale]" used `headers().get('X-NEXT-INTL-LOCALE')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at createHeadersAccessError (turbopack://[project]/node_modules/next/src/server/request/headers.ts:487:9)
    at getMessage (turbopack://[project]/node_modules/next/src/server/create-deduped-by-callsite-server-error-logger.ts:46:20)
    at warnForSyncAccess (turbopack://[project]/node_modules/next/src/server/request/headers.ts:473:2)
    at syncIODev (turbopack://[project]/node_modules/next/src/server/request/headers.ts:376:8)
    at <unknown> (turbopack://[project]/node_modules/next-intl/dist/esm/server/react-server/RequestLocaleLegacy.js:1:278)
    at apply (file:///home/wiibleyde/Alternance/lex-port-cartel/node_modules/next/dist/compiled/next-server/dist/compiled/react/cjs/react.react-server.development.js:888:26)
    at s (turbopack://[project]/node_modules/next-intl/dist/esm/server/react-server/RequestLocaleLegacy.js:1:996)
    at get locale [as locale] (turbopack://[project]/node_modules/next-intl/dist/esm/server/react-server/getConfig.js:1:874)
    at <unknown> (turbopack://[project]/src/i18n/request.ts:5:41)
    at <unknown> (turbopack://[project]/node_modules/next-intl/dist/esm/server/react-server/getConfig.js:1:939)
    at apply (file:///home/wiibleyde/Alternance/lex-port-cartel/node_modules/next/dist/compiled/next-server/dist/compiled/react/cjs/react.react-server.development.js:888:26)
    at <unknown> (turbopack://[project]/node_modules/next-intl/dist/esm/server/react-server/getConfig.js:1:1446)
    at apply (file:///home/wiibleyde/Alternance/lex-port-cartel/node_modules/next/dist/compiled/next-server/dist/compiled/react/cjs/react.react-server.development.js:888:26)
    at r (turbopack://[project]/node_modules/next-intl/dist/esm/react-server/useConfig.js:1:436)
    at o (turbopack://[project]/node_modules/next-intl/dist/esm/react-server/useTranslations.js:1:168)
    at Loading (turbopack://[project]/src/app/[locale]/loading.tsx:6:30)
> 1 | import{headers as e}from"next/headers";import{notFound as t}from"next/navigation";import{cache as n}from"react";import{HEADER_LOCALE_NAME as o}from"../../shared/constants.js";import{getCachedRequestLocale as r}from"./RequestLocaleCache.js";const i=n((function(){let n;try{n=e().get(o)}catch(e){throw e instanceof Error&&"DYNAMIC_SERVER_USAGE"===e.digest?new Error("Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `setRequestLocale` API to enable static rendering, see https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing#static-rendering",{cause:e}):e}return n||(console.error("\nUnable to find `next-intl` locale because the middleware didn't run on this request. See https://next-intl-docs.vercel.app/docs/routing/middleware#unable-to-find-locale. The `notFound()` function will be called as a result.\n"),t()),n}));function s(){return r()||i()}export{s as getRequestLocale};
```

With this packages :
  "dependencies": {
    "axios": "^1.7.7",
    "next": "^15.0.2",
    "next-intl": "^3.24.0",
    "react": "19.0.0-rc-69d4b800-20241021",
    "react-bootstrap-icons": "^1.11.4",
    "react-dom": "19.0.0-rc-69d4b800-20241021",
    "react-google-recaptcha-v3": "^1.10.1"
  },
  
  Any ideas if it's my fault ? (it's possible, I'm a junior developper)

**Comment by amannn** [comment]
Hey @Wiibleyde, nope—that's a different story. You're looking for this: [`await requestLocale`](https://next-intl-docs.vercel.app/blog/next-intl-3-22#await-request-locale).

**Comment by Wiibleyde** [comment]
Oh okay thanks ! *and sorry...*

**Comment by amannn** [comment]
I opened a PR yesterday over at the Next.js repo to address this: https://github.com/vercel/next.js/pull/73431

**Comment by rolandszoke-byborg** [comment]
Thank you for the fix @amannn although it is sad that they did not backport it to `v15.1`.

**Comment by amannn** [comment]
Yep, I've seen that `15.1.7` was released this week without the fix unfortunately. I've pinged the Next.js team on Tuesday to hopefully include the fix in the next patch version.

**Comment by service-paradis** [comment]
According to https://github.com/vercel/next.js/pull/76120, it looks like it might be backported in the upcoming release!

**Comment by damien-monni** [comment]
Thanks for the hard work @amannn!

I've tested it and deployed my app to Vercel and Netlify. Headers now appear on Vercel but not on Netlify. Do you see a reason why?

**Comment by damien-monni** [comment]
@amannn I checked with Netlify: https://answers.netlify.com/t/next-js-next-intl-middleware-not-setting-link-headers-on-netlify/140739/2.

I don’t have a definitive answer yet, but it seems that the Link header is present in the 307 response when accessing a URL without the locale at the end. However, it doesn’t appear when accessing a URL with the locale at the end. I reproduced this issue by forking the next-intl example and deploying it to Netlify, as shown in the support forum.

**Comment by razzeee** [comment]
What do we need to do for self hosted?

Right now we end up with this header:

```
link: <https://frontend-6d89795dcb-2zxqp/en/about>; rel="alternate"; hreflang="en", <https://frontend-6d89795dcb-2zxqp/en-GB/about>; rel="alternate"; hreflang="en-GB", <https://frontend-6d89795dcb-2zxqp/de/about>; rel="alternate"; hreflang="de", <https://frontend-6d89795dcb-2zxqp/fr/about>; rel="alternate"; hreflang="fr", <https://frontend-6d89795dcb-2zxqp/nb-NO/about>; rel="alternate"; hreflang="nb-NO", <https://frontend-6d89795dcb-2zxqp/tr/about>; rel="alternate"; hreflang="tr", <https://frontend-6d89795dcb-2zxqp/fi/about>; rel="alternate"; hreflang="fi", <https://frontend-6d89795dcb-2zxqp/id/about>; rel="alternate"; hreflang="id", <https://frontend-6d89795dcb-2zxqp/pl/about>; rel="alternate"; hreflang="pl", <https://frontend-6d89795dcb-2zxqp/pt-BR/about>; rel="alternate"; hreflang="pt-BR", <https://frontend-6d89795dcb-2zxqp/it/about>; rel="alternate"; hreflang="it", <https://frontend-6d89795dcb-2zxqp/ru/about>; rel="alternate"; hreflang="ru", <https://frontend-6d89795dcb-2zxqp/si/about>; rel="alternate"; hreflang="si", <https://frontend-6d89795dcb-2zxqp/vi/about>; rel="alternate"; hreflang="vi", <https://frontend-6d89795dcb-2zxqp/ar/about>; rel="alternate"; hreflang="ar", <https://frontend-6d89795dcb-2zxqp/es/about>; rel="alternate"; hreflang="es", <https://frontend-6d89795dcb-2zxqp/ja/about>; rel="alternate"; hreflang="ja", <https://frontend-6d89795dcb-2zxqp/cs/about>; rel="alternate"; hreflang="cs", <https://frontend-6d89795dcb-2zxqp/zh-Hans/about>; rel="alternate"; hreflang="zh-Hans", <https://frontend-6d89795dcb-2zxqp/bg/about>; rel="alternate"; hreflang="bg", <https://frontend-6d89795dcb-2zxqp/uk/about>; rel="alternate"; hreflang="uk", <https://frontend-6d89795dcb-2zxqp/et/about>; rel="alternate"; hreflang="et", <https://frontend-6d89795dcb-2zxqp/ca/about>; rel="alternate"; hreflang="ca", <https://frontend-6d89795dcb-2zxqp/el/about>; rel="alternate"; hreflang="el", <https://frontend-6d89795dcb-2zxqp/ta/about>; rel="alternate"; hreflang="ta", <https://frontend-6d89795dcb-2zxqp/fa/about>; rel="alternate"; hreflang="fa", <https://frontend-6d89795dcb-2zxqp/hi/about>; rel="alternate"; hreflang="hi", <https://frontend-6d89795dcb-2zxqp/bn/about>; rel="alternate"; hreflang="bn", <https://frontend-6d89795dcb-2zxqp/eo/about>; rel="alternate"; hreflang="eo", <https://frontend-6d89795dcb-2zxqp/lt/about>; rel="alternate"; hreflang="lt", <https://frontend-6d89795dcb-2zxqp/hr/about>; rel="alternate"; hreflang="hr", <https://frontend-6d89795dcb-2zxqp/be/about>; rel="alternate"; hreflang="be", <https://frontend-6d89795dcb-2zxqp/hu/about>; rel="alternate"; hreflang="hu", <https://frontend-6d89795dcb-2zxqp/nl/about>; rel="alternate"; hreflang="nl", <https://frontend-6d89795dcb-2zxqp/pt/about>; rel="alternate"; hreflang="pt", <https://frontend-6d89795dcb-2zxqp/zh-Hant/about>; rel="alternate"; hreflang="zh-Hant", <https://frontend-6d89795dcb-2zxqp/oc/about>; rel="alternate"; hreflang="oc", <https://frontend-6d89795dcb-2zxqp/da/about>; rel="alternate"; hreflang="da", <https://frontend-6d89795dcb-2zxqp/az/about>; rel="alternate"; hreflang="az", <https://frontend-6d89795dcb-2zxqp/he/about>; rel="alternate"; hreflang="he", <https://frontend-6d89795dcb-2zxqp/ro/about>; rel="alternate"; hreflang="ro", <https://frontend-6d89795dcb-2zxqp/hy/about>; rel="alternate"; hreflang="hy", <https://frontend-6d89795dcb-2zxqp/ko/about>; rel="alternate"; hreflang="ko", <https://frontend-6d89795dcb-2zxqp/sv/about>; rel="alternate"; hreflang="sv", <https://frontend-6d89795dcb-2zxqp/pa/about>; rel="alternate"; hreflang="pa", <https://frontend-6d89795dcb-2zxqp/sq/about>; rel="alternate"; hreflang="sq", <https://frontend-6d89795dcb-2zxqp/ia/about>; rel="alternate"; hreflang="ia", <https://frontend-6d89795dcb-2zxqp/ckb/about>; rel="alternate"; hreflang="ckb", <https://frontend-6d89795dcb-2zxqp/ga/about>; rel="alternate"; hreflang="ga", <https://frontend-6d89795dcb-2zxqp/kab/about>; rel="alternate"; hreflang="kab", <https://frontend-6d89795dcb-2zxqp/fil/about>; rel="alternate"; hreflang="fil", <https://frontend-6d89795dcb-2zxqp/br/about>; rel="alternate"; hreflang="br", <https://frontend-6d89795dcb-2zxqp/about>; rel="alternate"; hreflang="x-default"

```

You can test this by running `curl -I https://flathub.org/en/about `

**Comment by amannn** [comment]
@razzeee My guess would be that you're using a reverse proxy and it doesn't correctly set the `x-forwarded-host` header (see [Which alternate links are included?](https://next-intl.dev/docs/routing/configuration#alternate-links-details)).

**Comment by razzeee** [comment]
Thanks, fixed it https://github.com/flathub-infra/website/commit/f5af7e85d30b091cdc086497f333abfb27f5f42b
