### ISSUE TITLE
TypeError when using withNextIntl in combination with withContentlayer

### ISSUE THREAD

**Issue by alex289** [amannn/next-intl#188]
### Description

When using the withNextIntl inside the next.config.js in combination with withContentlayer (I didn't test it with other plugins) I get the following error. Both plugins work alone so I don't know where the problem occurs.

I use:
next-intl: 2.11.0-beta.7
Next 13 with the app directory

TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default(...)' as it is undefined.
    at Object.8534 (/Users/alex/dev/Portfolio/.next/server/chunks/290.js:32353:9)
    at __webpack_require__ (/Users/alex/dev/Portfolio/.next/server/webpack-runtime.js:25:42)
    at Object.2600 (/Users/alex/dev/Portfolio/.next/server/chunks/290.js:3236:15)
    at __webpack_require__ (/Users/alex/dev/Portfolio/.next/server/webpack-runtime.js:25:42)
    at Object.4638 (/Users/alex/dev/Portfolio/.next/server/chunks/290.js:31921:26)
    at __webpack_require__ (/Users/alex/dev/Portfolio/.next/server/webpack-runtime.js:25:42)
    at Object.3285 (/Users/alex/dev/Portfolio/.next/server/app/[locale]/page.js:377:67)
    at Function.__webpack_require__ (/Users/alex/dev/Portfolio/.next/server/webpack-runtime.js:25:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async collectGenerateParams (/Users/alex/dev/Portfolio/node_modules/.pnpm/next@13.1.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:714:17)

### Reproduction URL (CodeSandbox)

https://github.com/alex289/Portfolio/tree/feature/app_directory

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Run pnpm build or pnpm dev
3. See error: TypeError: Cannot destructure property… 

### Expected behaviour

No error at all.

**Comment by alex289** [comment]
Nevermind, the issue is coming from contentlayer. Thanks for the great work.

https://github.com/contentlayerdev/contentlayer/issues/341

**Comment by alex289** [comment]
The more I read into this the more unsure I get about where the error is coming from 😅

**Comment by amannn** [comment]
I've replied here: https://github.com/contentlayerdev/contentlayer/issues/341#issuecomment-1429313376
