### ISSUE TITLE
next-intl conflict with next v13.4.12

### ISSUE THREAD

**Issue by mkhavari01** [amannn/next-intl#443]
### Description

i have upgraded next version from v13.4.1 to v13.4.12 and next-int was working fine in the previous version but in the latest version of next it always bringing up this error message
`n [Error]: MISSING_MESSAGE
    at g (C:\Users\Mahdi Khavari\Desktop\Front\.next\server\chunks\145.js:92697:2895)
    at C:\Users\Mahdi Khavari\Desktop\Front\.next\server\chunks\145.js:92697:8922
    at Object.Sf [as useMemo] (C:\Users\Mahdi Khavari\Desktop\Front\node_modules\.pnpm\next@13.4.12_@babel+core@7.22.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\react-dom-experimental\cjs\react-dom-server.edge.production.min.js:105:241)
    at exports.useMemo (C:\Users\Mahdi Khavari\Desktop\Front\node_modules\.pnpm\next@13.4.12_@babel+core@7.22.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\react-experimental\cjs\react.production.min.js:31:125)
    at C:\Users\Mahdi Khavari\Desktop\Front\.next\server\chunks\145.js:92697:8895
    at exports.useTranslations (C:\Users\Mahdi Khavari\Desktop\Front\.next\server\chunks\145.js:92697:9183)
    at DialogComponent (C:\Users\Mahdi Khavari\Desktop\Front\.next\server\chunks\8189.js:68:63)
    at pg (C:\Users\Mahdi Khavari\Desktop\Front\node_modules\.pnpm\next@13.4.12_@babel+core@7.22.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\react-dom-experimental\cjs\react-dom-server.edge.production.min.js:118:273)
    at Z (C:\Users\Mahdi Khavari\Desktop\Front\node_modules\.pnpm\next@13.4.12_@babel+core@7.22.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\react-dom-experimental\cjs\react-dom-server.edge.production.min.js:125:91)
    at qg (C:\Users\Mahdi Khavari\Desktop\Front\node_modules\.pnpm\next@13.4.12_@babel+core@7.22.1_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\react-dom-experimental\cjs\react-dom-server.edge.production.min.js:128:155) {
  code: 'MISSING_MESSAGE',
  originalMessage: undefined
}`

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

N/A

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

i expect it not to give me this error message since it was working fine in previous version

**Comment by mkhavari01** [comment]
next-intl conflict with next v13.4.12 #443
