### ISSUE TITLE
Next js -H 127.0.0.1 problem

### ISSUE THREAD

**Issue by pixkk** [amannn/next-intl#524]
### Description

Next JS 13.5. If i use -H option in startup script (next dev -H 127.0.0.1) and visit 127.0.0.1:{port} (or localhost:{port}), i get loop of redirection to localhost:{port} or error "431 Request Header Fields Too Large".

Currently tested in server side (https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components), but problem exist in client side also. 

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://codesandbox.io/p/sandbox/next-intl-bug-template-app-forked-xj6t8q?file=%2Fpackage.json%3A10%2C20

(in Browser Console "Failed to load resource: the server responded with a status of 431 (Request Header Fields Too Large)")

### Reproduction description

Steps to reproduce:
1. https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components
2. Start dev (next dev -H 127.0.0.1)
3. Look in Network tab in Developer menu (F12).

### Expected behaviour

Page with site is opening (with and without language selector in url).

**Comment by jl75** [comment]
Might have to do with https://github.com/vercel/next.js/pull/54277

**Comment by amannn** [comment]
Thanks for the reproduction!

Hmm, I'm wondering if this needs to be fixed upstream. The error appears as soon as the middleware is added.

However I see this one:

```
Failed to proxy http://localhost:3000/en Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3000
}
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3000
}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at _res.setHeader (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:404:24)
    at _res.setHeader (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:404:24)
    at NodeNextResponse.setHeader (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-http/node.js:78:19)
    at DevServer.renderErrorImpl (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1720:17)
    at /Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1715:25
    at NextTracerImpl.trace (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/trace/tracer.js:90:20)
    at DevServer.renderError (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1714:41)
    at DevServer.renderError (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:830:22)
    at DevServer.handleRequestImpl (/Users/jan/Projects/amannn/next-intl/node_modules/.pnpm/next@13.5.1_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:683:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

It can be simplified to this middleware:

```tsx
import {NextRequest, NextResponse} from 'next/server';

export default function middleware(req: NextRequest) {
  const target = new URL('/en', req.nextUrl);
  return NextResponse.rewrite(target);
}

export const config = {
  matcher: ['/']
};
```

Did you search upstream bug reports? Might be worth adding a bug report in the Next.js repo.

**Comment by pixkk** [comment]
> Did you search upstream bug reports? Might be worth adding a bug report in the Next.js repo.

If i don`t use next-intl middleware from tutorial, all working fine. Next js working without errors without next-intl and 127.0.0.1.

**Comment by amannn** [comment]
I meant that it seems like the middleware doesn't work with the `-H` option generally, I'm not sure if this can be addressed by `next-intl`.

To move forward here, you could make a reproduction without the usage of `next-intl` with this middleware:

```tsx
import {NextRequest, NextResponse} from 'next/server';

export default function middleware(req: NextRequest) {
  const target = new URL('/en', req.nextUrl);
  return NextResponse.rewrite(target);
}

export const config = {
  matcher: ['/']
};
```

… and open an issue in the Next.js repo.

**Comment by jl75** [comment]
Silly me. I had commented out my matcher for testing purposes. When I reenabled the matcher below, everything worked again. Was not a problem with Next 13.4.x, but surfaced only after upgrading to 13.5.x.
```
export const config = {
matcher: [
    /*
     * Skip all paths that should not be internationalized
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```

**Comment by pixkk** [comment]
**Update** (for people, who search answer to this question).

**Solution**: use local IPV4 address of your PC (for example 192.168.2.105).
```node
  "scripts": {
    "dev": "next dev -H 192.168.2.105",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
```
