### ISSUE TITLE
useMemo error on build

### ISSUE THREAD

**Issue by yersultanur** [amannn/next-intl#551]
### Description

tried  through useEffect too, I think problem is with accessing window

```
    const isMobile = useMemo(() => {
        return window.matchMedia("(max-width: 768px)").matches
    }, [])
    const [sliderRef, instanceRef] = useKeenSlider<HTMLDivElement>(
        {
            loop: true,
            slides: {
                perView: isMobile ? 1 : 4,
                spacing: isMobile ? 0 : 15,
            },
            initial: 0,
            slideChanged(slider) {
                setCurrentSlide(slider.track.details.rel)
            },
            created() {
                setLoaded(true)
            },
        },
```

```
pnpm build

> hansa-landing-page@0.1.0 build C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page
> next build

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (3/6)  [=== ]
ReferenceError: window is not defined
    at C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3437
    at Object.rZ [as useMemo] (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:30300)
    at t.useMemo (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:75:7338)
    at CarouselSlider (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3393)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:35308)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:48158)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)
    at ny (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:53901)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:45663)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)
ReferenceError: window is not defined
    at C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3437
    at Object.rZ [as useMemo] (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:30300)
    at t.useMemo (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:75:7338)
    at CarouselSlider (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3393)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:35308)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:48158)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)
    at ny (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:53901)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:45663)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)

Error occurred prerendering page "/kz". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3437
    at Object.rZ [as useMemo] (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:30300)
    at t.useMemo (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:75:7338)
    at CarouselSlider (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3393)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:35308)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:48158)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)
    at ny (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:53901)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:45663)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)

Error occurred prerendering page "/ru". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3437
    at Object.rZ [as useMemo] (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:30300)
    at t.useMemo (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:75:7338)
    at CarouselSlider (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\.next\server\app\[locale]\(hansa)\page.js:1:3393)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:35308)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:48158)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:50922)
    at ny (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:53901)
    at nd (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:27:45663)
    at nh (C:\Users\ersin\Desktop\hansa-landing-page\hansa-landing-page\node_modules\.pnpm\next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\nex ✓ Generating static pages (6/6)                                                                                                                                                           

> Export encountered errors on following paths:
        /[locale]/(hansa)/page: /kz
        /[locale]/(hansa)/page: /ru
 ELIFECYCLE  Command failed with exit code 1.
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

nope

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

work fine on window measure

**Comment by amannn** [comment]
>  I think problem is with accessing window

Yep, that seems to be the problem.

This issue is not related to `next-intl`, therefore I'll close it—I hope you understand.
