### ISSUE TITLE
Upgrading from 3.0.0-beta.19 to 3.1.0 gives a lot of errors

### ISSUE THREAD

**Issue by oaj** [amannn/next-intl#649]
### Description

It can build fine with:
"next": "^13.5.6",
"next-intl": "3.0.0-beta.19",

when try to upgrade next-intl to 3.1.0, I get a lot of errors when builing. At the same time I upgrade next to 14.0.3

It gives an error like this for each path in the app

Error occurred prerendering page "/es/about". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering, see https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#static-rendering
    at /home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65554
    at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:179223
    at l (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:66180)
    at f (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:64882)
    at h (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:64966)
    at v (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65053)
    at b (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65310)
    at em (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Object.toJSON (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659)
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering, see https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#static-rendering
    at /home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65554
    at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:179223
    ... 5 lines matching cause stack trace ...
    at em (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Object.toJSON (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659) {
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at l (/home/oaj/projects/kanowa_app/.next/server/chunks/4312.js:1:3737)
      at d (/home/oaj/projects/kanowa_app/.next/server/chunks/4312.js:1:1093)
      at /home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65456
      at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:179223
      at l (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:66180)
      at f (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:64882)
      at h (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:64966)
      at v (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65053)
      at b (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65310)
      at em (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381) {
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering, see https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#static-rendering
    at /home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65554
    at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:179223
    ... 5 lines matching cause stack trace ...
    at em (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381)
    at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140081
    at Object.toJSON (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143659) {
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at l (/home/oaj/projects/kanowa_app/.next/server/chunks/4312.js:1:3737)
      at d (/home/oaj/projects/kanowa_app/.next/server/chunks/4312.js:1:1093)
      at /home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65456
      at /home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:179223
      at l (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:66180)
      at f (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:64882)
      at h (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:64966)
      at v (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65053)
      at b (/home/oaj/projects/kanowa_app/.next/server/chunks/5121.js:124:65310)
      at em (/home/oaj/projects/kanowa_app/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128381) {
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}

This the about page mentiont in the error  message:

```
"use client"
import {NextPage} from "next";

export default function About() {

    return (
        <div>
            <h1>About</h1>
        </div>
    )
}


```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

*

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

No errors

**Comment by amannn** [comment]
Sorry, there was no reproduction provided, therefore I can not look into this.

Please be careful to review [the release notes for 3.0](https://next-intl-docs.vercel.app/blog/next-intl-3-0) and consult [the examples](https://next-intl-docs.vercel.app/examples) when in doubt.
