### ISSUE TITLE
Error: `getRequestConfig` is not supported in Client Components.

### ISSUE THREAD

**Issue by Robin-Ln** [amannn/next-intl#685]
### Description

when i upgrade to 3.2.1 from 3.2.0 i get this error : 

```
 ⨯ Error: `getRequestConfig` is not supported in Client Components.
    at <unknown> (webpack-internal:///(middleware)/./node_modules/.pnpm/next-intl@3.2.1_next@14.0.3_react@18.2.0/node_modules/next-intl/dist/development/server/react-client/index.js:13)
    at eval (webpack-internal:///(middleware)/./node_modules/.pnpm/next-intl@3.2.1_next@14.0.3_react@18.2.0/node_modules/next-intl/dist/development/server/react-client/index.js:13:15)
    at eval (webpack-internal:///(middleware)/./src/configs/i18n.ts:27:132)
    at (middleware)/./src/configs/i18n.ts (file:///Users/rlouarn/git/programme-tz-2023/.next/server/src/middleware.js:740:1)
    at __webpack_require__ (file:///Users/rlouarn/git/programme-tz-2023/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///Users/rlouarn/git/programme-tz-2023/.next/server/edge-runtime-webpack.js:306:21)
    at eval (webpack-internal:///(middleware)/./src/middleware.ts:6:71)
    at (middleware)/./src/middleware.ts (file:///Users/rlouarn/git/programme-tz-2023/.next/server/src/middleware.js:751:1)
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://gitlab.com/robin.louarn/programme-tz-2023

### Reproduction description

Steps to reproduce:
1. upgrade to 3.2.1
2. run pnpm app:dev
3. See error:  `⨯ Error: 'getRequestConfig' is not supported in Client Components.`

### Expected behaviour

Work like in version 3.2.0

**Comment by Rikard-Johansson97** [comment]
I get the same. next-intl@3.2.1 and next@14.0.3.

I downgraded to 3.2.0 and now it works again

**Comment by M-Nasser-M** [comment]
i got the same issue next-intl@3.2.1 and next@14.0.3
downgrading also works for me
