### ISSUE TITLE
Take the name of the JSON file as namespace when splitting localization files

### ISSUE THREAD

**Issue by SalahAdDin** [amannn/next-intl#831]
### Is your feature request related to a problem? Please describe.

We decided to work with this package to handle the website internationalization.

We implemented [splitting files](https://next-intl-docs.vercel.app/docs/usage/configuration#messages) to have it more organized, It follows like this:
![image](https://github.com/amannn/next-intl/assets/5034215/5434daf8-e74b-4dbd-8fc3-e18e6a7857d1)

Unfortunately, It does not get the file names as namespaces as one might guess:
```
IntlError: MISSING_MESSAGE: Could not resolve `home` in messages for locale `en`.
    at getMessagesOrError (webpack-internal:///(rsc)/./node_modules/.pnpm/use-intl@3.5.4_react@18.2.0/node_modules/use-intl/dist/development/createFormatter-3fcd09b9.js:101:27)
    at Object.createBaseTranslator (webpack-internal:///(rsc)/./node_modules/.pnpm/use-intl@3.5.4_react@18.2.0/node_modules/use-intl/dist/development/createFormatter-3fcd09b9.js:119:29)
    at createTranslatorImpl (webpack-internal:///(rsc)/./node_modules/.pnpm/use-intl@3.5.4_react@18.2.0/node_modules/use-intl/dist/development/core.js:15:28)
    at createTranslator (webpack-internal:///(rsc)/./node_modules/.pnpm/use-intl@3.5.4_react@18.2.0/node_modules/use-intl/dist/development/core.js:35:12)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/next-intl@3.5.4_next@14.1.0_react@18.2.0/node_modules/next-intl/dist/esm/react-server/getTranslator.js:13:75)
    at /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:360290
    at o (webpack-internal:///(rsc)/./node_modules/.pnpm/next-intl@3.5.4_next@14.1.0_react@18.2.0/node_modules/next-intl/dist/esm/react-server/useTranslations.js:13:73)
    at Home (webpack-internal:///(rsc)/./src/app/[locale]/page.tsx:16:68)
    at ej (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:264151)
    at ez (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:267802)
    at eH (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:268559)
    at Timeout._onTimeout (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:265057)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'MISSING_MESSAGE',
  originalMessage: 'Could not resolve `home` in messages for locale `en`.'
}
```

### Describe the solution you'd like

It would be nice that the package would make the name of the localization file as the name space itself.

Since we split the `json` in chunks to get it more ordered, splitting by namespaces is the best option, and from it, it would be nice to have such behaviour by default.

### Describe alternatives you've considered

Right now we can solve it either:
- by adding the namespace as key, i.e., `{ "home": ...}`.
- by adding a key name on the configuration file: `home: { ...(await import(`./locales/${locale}/home.json`)).default }`

**Comment by amannn** [comment]
Please see https://github.com/amannn/next-intl/issues/832#issuecomment-1923353842
